package FIle_Sharing;


import dao.FileU;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import javax.swing.JOptionPane;
import model.Files;
import dao.filesdao;
import java.io.File;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.table.TableModel;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author DELL
 */
public class client extends javax.swing.JFrame {

    public String email;
    String filepath;
    
    public client() {
        initComponents();
        btnup.setEnabled(false);
    }
    
    public void ValidateField(){
        String files1 = txtname.getText();
        String files2 = txtsize.getText();
        String files3 = chooseBtn.getText();
        
        if(!files1.equals("") && !files2.equals("") && !files3.equals(""))
        btnup.setEnabled(true);
        else
            btnup.setEnabled(false);
    }

    public client(String useremail) {
        initComponents();
        email = useremail;
        if(!email.equals("admin@gmail.com")){
            btndelete.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnup = new javax.swing.JButton();
        btndown = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtsize = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chooseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("File Server System");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 240, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Available files");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 30));

        btnup.setBackground(new java.awt.Color(51, 0, 102));
        btnup.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnup.setForeground(new java.awt.Color(255, 255, 255));
        btnup.setText("Upload");
        btnup.setPreferredSize(new java.awt.Dimension(100, 30));
        btnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupActionPerformed(evt);
            }
        });
        jPanel1.add(btnup, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        btndown.setBackground(new java.awt.Color(51, 0, 102));
        btndown.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btndown.setForeground(new java.awt.Color(255, 255, 255));
        btndown.setText("Download");
        btndown.setPreferredSize(new java.awt.Dimension(100, 30));
        btndown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndownActionPerformed(evt);
            }
        });
        jPanel1.add(btndown, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        btnLogout.setBackground(new java.awt.Color(51, 0, 102));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setPreferredSize(new java.awt.Dimension(100, 30));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btnexit.setBackground(new java.awt.Color(51, 0, 102));
        btnexit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 255, 255));
        btnexit.setText("Exit");
        btnexit.setPreferredSize(new java.awt.Dimension(100, 30));
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));

        btndelete.setBackground(new java.awt.Color(51, 0, 102));
        btndelete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("Delete");
        btndelete.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        TBl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "fileID", "fileName", "Size", "file_path"
            }
        ));
        TBl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBlMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, 170));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Upload File");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 200, -1));

        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 260, -1));

        txtsize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsizeKeyReleased(evt);
            }
        });
        jPanel1.add(txtsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 260, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("File Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 80, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Size:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("file_path:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        chooseBtn.setText("Choose a file");
        chooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(chooseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 260, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndownActionPerformed
          
        
        
        String name = null;
        String path = null;
        FileU f = new FileU(name,path);
        f.down();
    }//GEN-LAST:event_btndownActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to exit?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to Logout?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
           Files files = new Files();
           files.setFilename(txtname.getText());
           files.setSize(txtsize.getText());
           files.setFile_path(filepath);
           filesdao.Upload(files);
           setVisible(false);
           FileU fu = new FileU(txtname.getText(),filepath.toString());
           fu.up();
           new client().setVisible(true);
    }//GEN-LAST:event_btnupActionPerformed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        ValidateField();
    }//GEN-LAST:event_txtnameKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        DefaultTableModel dtm = (DefaultTableModel) TBl.getModel();
        ArrayList<Files> list = filesdao.getAllRecords();
        Iterator<Files> itr = list.iterator();
        while(itr.hasNext()){
            Files filesObj = itr.next();
            dtm.addRow(new Object[]{
                filesObj.getFileID(),filesObj.getFilename(),filesObj.getSize(),filesObj.getFile_path()
            });
        }
    }//GEN-LAST:event_formComponentShown

    private void TBlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBlMouseClicked
        int index = TBl.getSelectedRow();
        TableModel model = TBl.getModel();
        String fileID = model.getValueAt(index,0).toString();
        String fileName = model.getValueAt(index,0).toString();
        String Size = model.getValueAt(index,0).toString();
        String file_path = model.getValueAt(index,0).toString();
        JOptionPane.showConfirmDialog(null, "Do you want to delete?"+fileName+,+Size+,+file_path+,"Files","select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            filesdao.delete(fileID);
            setVisible(false);
            new client().setVisible(true);
        }
    }//GEN-LAST:event_TBlMouseClicked

    private void txtsizeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsizeKeyReleased
        ValidateField();
    }//GEN-LAST:event_txtsizeKeyReleased

    private void chooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser f = new JFileChooser();
        int returnV = f.showOpenDialog(null);
        
        if(returnV == JFileChooser.APPROVE_OPTION){
            File selectedFIle = f.getSelectedFile();
            this.filepath = selectedFIle.getAbsolutePath();
        }
        
    }//GEN-LAST:event_chooseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBl;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndown;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnup;
    private javax.swing.JButton chooseBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsize;
    // End of variables declaration//GEN-END:variables
}
